name: Deploy on production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - run: echo "Deploying to production server..."
      

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#       - name: Install dependencies
#         run: npm install
#       - name: Build the project
#         run: npm run build
#       - name: Deploy to production server
#         run: |
#           scp -r ./dist user@your-production-server:/path/to/deploy
#           ssh user@your-production-server "cd /path/to/deploy && npm install --production && pm2 restart your-app"