name: Deploy on production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy to Production
    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          touch /home/runner/.ssh/known_hosts
          echo "${{ secrets.KNOWN_HOSTS }}" &> /home/runner/.ssh/known_hosts
          chmod 700 /home/runner/ssh_key
          ssh -i ~/ssh_key root@64.227.147.124 -t "cd MERN-todo-monorepo/ && git pull origin mastre && npm --workspace=client run build && pm2 start ecosystem.config.js"
      

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: '18'
#       - name: Install dependencies
#         run: npm install
#       - name: Build the project
#         run: npm run build
#       - name: Deploy to production server
#         run: |
#           scp -r ./dist user@your-production-server:/path/to/deploy
#           ssh user@your-production-server "cd /path/to/deploy && npm install --production && pm2 restart your-app"